/* automatically generated by rust-bindgen 0.72.1 */

pub const HS_VERSION_STRING: &[u8; 18] = b"5.4.12 2026-04-23\0";
pub const HS_VERSION_32BIT: u32 = 84151296;
pub const HS_MAJOR: u32 = 5;
pub const HS_MINOR: u32 = 4;
pub const HS_PATCH: u32 = 12;
pub const HS_SUCCESS: u32 = 0;
pub const HS_INVALID: i32 = -1;
pub const HS_NOMEM: i32 = -2;
pub const HS_SCAN_TERMINATED: i32 = -3;
pub const HS_COMPILER_ERROR: i32 = -4;
pub const HS_DB_VERSION_ERROR: i32 = -5;
pub const HS_DB_PLATFORM_ERROR: i32 = -6;
pub const HS_DB_MODE_ERROR: i32 = -7;
pub const HS_BAD_ALIGN: i32 = -8;
pub const HS_BAD_ALLOC: i32 = -9;
pub const HS_SCRATCH_IN_USE: i32 = -10;
pub const HS_ARCH_ERROR: i32 = -11;
pub const HS_INSUFFICIENT_SPACE: i32 = -12;
pub const HS_UNKNOWN_ERROR: i32 = -13;
pub const HS_EXT_FLAG_MIN_OFFSET: u32 = 1;
pub const HS_EXT_FLAG_MAX_OFFSET: u32 = 2;
pub const HS_EXT_FLAG_MIN_LENGTH: u32 = 4;
pub const HS_EXT_FLAG_EDIT_DISTANCE: u32 = 8;
pub const HS_EXT_FLAG_HAMMING_DISTANCE: u32 = 16;
pub const HS_FLAG_CASELESS: u32 = 1;
pub const HS_FLAG_DOTALL: u32 = 2;
pub const HS_FLAG_MULTILINE: u32 = 4;
pub const HS_FLAG_SINGLEMATCH: u32 = 8;
pub const HS_FLAG_ALLOWEMPTY: u32 = 16;
pub const HS_FLAG_UTF8: u32 = 32;
pub const HS_FLAG_UCP: u32 = 64;
pub const HS_FLAG_PREFILTER: u32 = 128;
pub const HS_FLAG_SOM_LEFTMOST: u32 = 256;
pub const HS_FLAG_COMBINATION: u32 = 512;
pub const HS_FLAG_QUIET: u32 = 1024;
pub const HS_CPU_FEATURES_AVX2: u32 = 4;
pub const HS_CPU_FEATURES_AVX512: u32 = 8;
pub const HS_CPU_FEATURES_AVX512VBMI: u32 = 16;
pub const HS_TUNE_FAMILY_GENERIC: u32 = 0;
pub const HS_TUNE_FAMILY_SNB: u32 = 1;
pub const HS_TUNE_FAMILY_IVB: u32 = 2;
pub const HS_TUNE_FAMILY_HSW: u32 = 3;
pub const HS_TUNE_FAMILY_SLM: u32 = 4;
pub const HS_TUNE_FAMILY_BDW: u32 = 5;
pub const HS_TUNE_FAMILY_SKL: u32 = 6;
pub const HS_TUNE_FAMILY_SKX: u32 = 7;
pub const HS_TUNE_FAMILY_GLM: u32 = 8;
pub const HS_TUNE_FAMILY_ICL: u32 = 9;
pub const HS_TUNE_FAMILY_ICX: u32 = 10;
pub const HS_MODE_BLOCK: u32 = 1;
pub const HS_MODE_NOSTREAM: u32 = 1;
pub const HS_MODE_STREAM: u32 = 2;
pub const HS_MODE_VECTORED: u32 = 4;
pub const HS_MODE_SOM_HORIZON_LARGE: u32 = 16777216;
pub const HS_MODE_SOM_HORIZON_MEDIUM: u32 = 33554432;
pub const HS_MODE_SOM_HORIZON_SMALL: u32 = 67108864;
pub const HS_OFFSET_PAST_HORIZON: i32 = -1;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hs_database {
    _unused: [u8; 0],
}
pub type hs_database_t = hs_database;
pub type hs_error_t = ::std::os::raw::c_int;
unsafe extern "C" {
    pub fn hs_free_database(db: *mut hs_database_t) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_serialize_database(
        db: *const hs_database_t,
        bytes: *mut *mut ::std::os::raw::c_char,
        length: *mut usize,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_deserialize_database(
        bytes: *const ::std::os::raw::c_char,
        length: usize,
        db: *mut *mut hs_database_t,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_deserialize_database_at(
        bytes: *const ::std::os::raw::c_char,
        length: usize,
        db: *mut hs_database_t,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_stream_size(database: *const hs_database_t, stream_size: *mut usize) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_database_size(
        database: *const hs_database_t,
        database_size: *mut usize,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_serialized_database_size(
        bytes: *const ::std::os::raw::c_char,
        length: usize,
        deserialized_size: *mut usize,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_database_info(
        database: *const hs_database_t,
        info: *mut *mut ::std::os::raw::c_char,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_serialized_database_info(
        bytes: *const ::std::os::raw::c_char,
        length: usize,
        info: *mut *mut ::std::os::raw::c_char,
    ) -> hs_error_t;
}
pub type hs_alloc_t =
    ::std::option::Option<unsafe extern "C" fn(size: usize) -> *mut ::std::os::raw::c_void>;
pub type hs_free_t = ::std::option::Option<unsafe extern "C" fn(ptr: *mut ::std::os::raw::c_void)>;
unsafe extern "C" {
    pub fn hs_set_allocator(alloc_func: hs_alloc_t, free_func: hs_free_t) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_set_database_allocator(alloc_func: hs_alloc_t, free_func: hs_free_t) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_set_misc_allocator(alloc_func: hs_alloc_t, free_func: hs_free_t) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_set_scratch_allocator(alloc_func: hs_alloc_t, free_func: hs_free_t) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_set_stream_allocator(alloc_func: hs_alloc_t, free_func: hs_free_t) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn hs_valid_platform() -> hs_error_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hs_compile_error {
    pub message: *mut ::std::os::raw::c_char,
    pub expression: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of hs_compile_error"][::std::mem::size_of::<hs_compile_error>() - 16usize];
    ["Alignment of hs_compile_error"][::std::mem::align_of::<hs_compile_error>() - 8usize];
    ["Offset of field: hs_compile_error::message"]
        [::std::mem::offset_of!(hs_compile_error, message) - 0usize];
    ["Offset of field: hs_compile_error::expression"]
        [::std::mem::offset_of!(hs_compile_error, expression) - 8usize];
};
pub type hs_compile_error_t = hs_compile_error;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hs_platform_info {
    pub tune: ::std::os::raw::c_uint,
    pub cpu_features: ::std::os::raw::c_ulonglong,
    pub reserved1: ::std::os::raw::c_ulonglong,
    pub reserved2: ::std::os::raw::c_ulonglong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of hs_platform_info"][::std::mem::size_of::<hs_platform_info>() - 32usize];
    ["Alignment of hs_platform_info"][::std::mem::align_of::<hs_platform_info>() - 8usize];
    ["Offset of field: hs_platform_info::tune"]
        [::std::mem::offset_of!(hs_platform_info, tune) - 0usize];
    ["Offset of field: hs_platform_info::cpu_features"]
        [::std::mem::offset_of!(hs_platform_info, cpu_features) - 8usize];
    ["Offset of field: hs_platform_info::reserved1"]
        [::std::mem::offset_of!(hs_platform_info, reserved1) - 16usize];
    ["Offset of field: hs_platform_info::reserved2"]
        [::std::mem::offset_of!(hs_platform_info, reserved2) - 24usize];
};
pub type hs_platform_info_t = hs_platform_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hs_expr_info {
    pub min_width: ::std::os::raw::c_uint,
    pub max_width: ::std::os::raw::c_uint,
    pub unordered_matches: ::std::os::raw::c_char,
    pub matches_at_eod: ::std::os::raw::c_char,
    pub matches_only_at_eod: ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of hs_expr_info"][::std::mem::size_of::<hs_expr_info>() - 12usize];
    ["Alignment of hs_expr_info"][::std::mem::align_of::<hs_expr_info>() - 4usize];
    ["Offset of field: hs_expr_info::min_width"]
        [::std::mem::offset_of!(hs_expr_info, min_width) - 0usize];
    ["Offset of field: hs_expr_info::max_width"]
        [::std::mem::offset_of!(hs_expr_info, max_width) - 4usize];
    ["Offset of field: hs_expr_info::unordered_matches"]
        [::std::mem::offset_of!(hs_expr_info, unordered_matches) - 8usize];
    ["Offset of field: hs_expr_info::matches_at_eod"]
        [::std::mem::offset_of!(hs_expr_info, matches_at_eod) - 9usize];
    ["Offset of field: hs_expr_info::matches_only_at_eod"]
        [::std::mem::offset_of!(hs_expr_info, matches_only_at_eod) - 10usize];
};
pub type hs_expr_info_t = hs_expr_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hs_expr_ext {
    pub flags: ::std::os::raw::c_ulonglong,
    pub min_offset: ::std::os::raw::c_ulonglong,
    pub max_offset: ::std::os::raw::c_ulonglong,
    pub min_length: ::std::os::raw::c_ulonglong,
    pub edit_distance: ::std::os::raw::c_uint,
    pub hamming_distance: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of hs_expr_ext"][::std::mem::size_of::<hs_expr_ext>() - 40usize];
    ["Alignment of hs_expr_ext"][::std::mem::align_of::<hs_expr_ext>() - 8usize];
    ["Offset of field: hs_expr_ext::flags"][::std::mem::offset_of!(hs_expr_ext, flags) - 0usize];
    ["Offset of field: hs_expr_ext::min_offset"]
        [::std::mem::offset_of!(hs_expr_ext, min_offset) - 8usize];
    ["Offset of field: hs_expr_ext::max_offset"]
        [::std::mem::offset_of!(hs_expr_ext, max_offset) - 16usize];
    ["Offset of field: hs_expr_ext::min_length"]
        [::std::mem::offset_of!(hs_expr_ext, min_length) - 24usize];
    ["Offset of field: hs_expr_ext::edit_distance"]
        [::std::mem::offset_of!(hs_expr_ext, edit_distance) - 32usize];
    ["Offset of field: hs_expr_ext::hamming_distance"]
        [::std::mem::offset_of!(hs_expr_ext, hamming_distance) - 36usize];
};
pub type hs_expr_ext_t = hs_expr_ext;
unsafe extern "C" {
    pub fn hs_compile(
        expression: *const ::std::os::raw::c_char,
        flags: ::std::os::raw::c_uint,
        mode: ::std::os::raw::c_uint,
        platform: *const hs_platform_info_t,
        db: *mut *mut hs_database_t,
        error: *mut *mut hs_compile_error_t,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_compile_multi(
        expressions: *const *const ::std::os::raw::c_char,
        flags: *const ::std::os::raw::c_uint,
        ids: *const ::std::os::raw::c_uint,
        elements: ::std::os::raw::c_uint,
        mode: ::std::os::raw::c_uint,
        platform: *const hs_platform_info_t,
        db: *mut *mut hs_database_t,
        error: *mut *mut hs_compile_error_t,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_compile_ext_multi(
        expressions: *const *const ::std::os::raw::c_char,
        flags: *const ::std::os::raw::c_uint,
        ids: *const ::std::os::raw::c_uint,
        ext: *const *const hs_expr_ext_t,
        elements: ::std::os::raw::c_uint,
        mode: ::std::os::raw::c_uint,
        platform: *const hs_platform_info_t,
        db: *mut *mut hs_database_t,
        error: *mut *mut hs_compile_error_t,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_compile_lit(
        expression: *const ::std::os::raw::c_char,
        flags: ::std::os::raw::c_uint,
        len: usize,
        mode: ::std::os::raw::c_uint,
        platform: *const hs_platform_info_t,
        db: *mut *mut hs_database_t,
        error: *mut *mut hs_compile_error_t,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_compile_lit_multi(
        expressions: *const *const ::std::os::raw::c_char,
        flags: *const ::std::os::raw::c_uint,
        ids: *const ::std::os::raw::c_uint,
        lens: *const usize,
        elements: ::std::os::raw::c_uint,
        mode: ::std::os::raw::c_uint,
        platform: *const hs_platform_info_t,
        db: *mut *mut hs_database_t,
        error: *mut *mut hs_compile_error_t,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_free_compile_error(error: *mut hs_compile_error_t) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_expression_info(
        expression: *const ::std::os::raw::c_char,
        flags: ::std::os::raw::c_uint,
        info: *mut *mut hs_expr_info_t,
        error: *mut *mut hs_compile_error_t,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_expression_ext_info(
        expression: *const ::std::os::raw::c_char,
        flags: ::std::os::raw::c_uint,
        ext: *const hs_expr_ext_t,
        info: *mut *mut hs_expr_info_t,
        error: *mut *mut hs_compile_error_t,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_populate_platform(platform: *mut hs_platform_info_t) -> hs_error_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hs_stream {
    _unused: [u8; 0],
}
pub type hs_stream_t = hs_stream;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hs_scratch {
    _unused: [u8; 0],
}
pub type hs_scratch_t = hs_scratch;
pub type match_event_handler = ::std::option::Option<
    unsafe extern "C" fn(
        id: ::std::os::raw::c_uint,
        from: ::std::os::raw::c_ulonglong,
        to: ::std::os::raw::c_ulonglong,
        flags: ::std::os::raw::c_uint,
        context: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
unsafe extern "C" {
    pub fn hs_open_stream(
        db: *const hs_database_t,
        flags: ::std::os::raw::c_uint,
        stream: *mut *mut hs_stream_t,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_scan_stream(
        id: *mut hs_stream_t,
        data: *const ::std::os::raw::c_char,
        length: ::std::os::raw::c_uint,
        flags: ::std::os::raw::c_uint,
        scratch: *mut hs_scratch_t,
        onEvent: match_event_handler,
        ctxt: *mut ::std::os::raw::c_void,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_close_stream(
        id: *mut hs_stream_t,
        scratch: *mut hs_scratch_t,
        onEvent: match_event_handler,
        ctxt: *mut ::std::os::raw::c_void,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_reset_stream(
        id: *mut hs_stream_t,
        flags: ::std::os::raw::c_uint,
        scratch: *mut hs_scratch_t,
        onEvent: match_event_handler,
        context: *mut ::std::os::raw::c_void,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_copy_stream(to_id: *mut *mut hs_stream_t, from_id: *const hs_stream_t) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_reset_and_copy_stream(
        to_id: *mut hs_stream_t,
        from_id: *const hs_stream_t,
        scratch: *mut hs_scratch_t,
        onEvent: match_event_handler,
        context: *mut ::std::os::raw::c_void,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_compress_stream(
        stream: *const hs_stream_t,
        buf: *mut ::std::os::raw::c_char,
        buf_space: usize,
        used_space: *mut usize,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_expand_stream(
        db: *const hs_database_t,
        stream: *mut *mut hs_stream_t,
        buf: *const ::std::os::raw::c_char,
        buf_size: usize,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_reset_and_expand_stream(
        to_stream: *mut hs_stream_t,
        buf: *const ::std::os::raw::c_char,
        buf_size: usize,
        scratch: *mut hs_scratch_t,
        onEvent: match_event_handler,
        context: *mut ::std::os::raw::c_void,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_scan(
        db: *const hs_database_t,
        data: *const ::std::os::raw::c_char,
        length: ::std::os::raw::c_uint,
        flags: ::std::os::raw::c_uint,
        scratch: *mut hs_scratch_t,
        onEvent: match_event_handler,
        context: *mut ::std::os::raw::c_void,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_scan_vector(
        db: *const hs_database_t,
        data: *const *const ::std::os::raw::c_char,
        length: *const ::std::os::raw::c_uint,
        count: ::std::os::raw::c_uint,
        flags: ::std::os::raw::c_uint,
        scratch: *mut hs_scratch_t,
        onEvent: match_event_handler,
        context: *mut ::std::os::raw::c_void,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_alloc_scratch(
        db: *const hs_database_t,
        scratch: *mut *mut hs_scratch_t,
    ) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_clone_scratch(src: *const hs_scratch_t, dest: *mut *mut hs_scratch_t) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_scratch_size(scratch: *const hs_scratch_t, scratch_size: *mut usize) -> hs_error_t;
}
unsafe extern "C" {
    pub fn hs_free_scratch(scratch: *mut hs_scratch_t) -> hs_error_t;
}
